; BREPO_MITI.ini - kontrola wersji (wersja firmowa idzie na repo jako latest.ini)
[Latest]
Version=1.0.0.0
Sha256=5B7C1A0F2CEA3A377D612322DC68E5E67E2C66FA2AF54B8008CF50DAA24024A0
Date=2026-07-15
Url=https://github.com/brepo-poland/MITI/releases/latest/download/BREPO_MITI.exe
