; BREPO_MITI.ini - kontrola wersji (wersja firmowa idzie na repo jako latest.ini)
[Latest]
Version=1.0.0.0
Sha256=EA4E32A2AF373F6A2D37A7229ABF7CE3BC695EDFC9A3FDEB56E1C06534D2874A
Date=2026-07-15
Url=https://github.com/brepo-poland/MITI/releases/latest/download/BREPO_MITI.exe
